### PR TITLE
Add node 12.4.0 support

### PR DESCRIPTION
**Pull request by ReimuNotMoe**
Made some changes so it (at least) compiles & usable.

There are still some warnings remain to be solved. I tried my best to replace all deprecated usages with (working) new ones, however almost all new ones have return values, and they're ignored for now.

It's not tested on old versions.

### CODE REVIEW

**Comment by vbraun** [comment]
Any chance of getting this fixed? Node 12 is going to be the default in a lot of distros real soon, e.g. Fedora 31. Many js dev tools indirectly depend on this package, so this is going to affect a lot of users...

**Comment by c4milo** [comment]
I will review today, thanks for the gentle ping.

**Comment by redneb** [comment]
Any updates on this one?

**Comment by redneb** [comment]
Now that this is merged, I tested it from HEAD (commit ee7efbc4add94691418cc2c96d56f7712d0b6873) and it appears that it brings back a problem similar to #67: if the callback passed to `inotify` waits on a promise, it might take longer time than necessary or it might even get stuck indefinitely. Here's a minimal example:

	const Inotify = require("inotify").Inotify;
	
	async function test() {
	}
	
	new Inotify().addWatch({
		path: ".",
		watch_for: Inotify.IN_ALL_EVENTS,
		callback: async () => {
			console.time("test");
			await test();
			console.timeEnd("test");
		},
	});

Run this and from a different terminal do `touch .`. The time it takes to run the (trivial) function `test` should have been <1ms, but not it takes much longer, or it even hangs indefinitely.

The same problem happens with `process.nextTick` and `queueMicrotask`.

**Pull request merged**
