### PR TITLE
Upgrading to NAN 2.x

### PR DESCRIPTION
**Pull request by edsadr**

### CODE REVIEW

**Comment by c4milo** [comment]
@edsadr, here are the results of my tests on your branch: 

**Node:** 
* 0.10.x: Works
* 0.12.x: Compiles but the module does not longer work

**io.js:**
* 1.x: Works
* 2.x: Works
* 3.x: Does not compile

**Comment by c4milo** [comment]
@edsadr Nice work. I'm going to give another round of testing just in case, before I merge it.

**Comment by c4milo** [comment]
I already pushed version 1.4.0 to NPM, including these changes. Thanks again @edsadr.

**Comment by edsadr** [comment]
:+1:  ... will work on deprectaion message in io.js v 3.0.0 and later will add some testing so would be easier to support more versions

**Comment by c4milo** [comment]
Thanks!

**Pull request merged**
